# Upon pushing to the main branch it runs all tests.
#
# Copyright (c) 2022 AlertAvert.com.  All rights reserved.
# Author: Marco Massenzio (marco@alertavert.com)
#
name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate Certs
      run: |
        export GOPATH=/opt/go
        mkdir -p $GOPATH/bin
        export PATH=$GOPATH/bin:$PATH
        go install github.com/cloudflare/cfssl/cmd/cfssl@v1.6.3
        go install github.com/cloudflare/cfssl/cmd/cfssljson@v1.6.3
        make gencert
    - name: Test
      run: |
        go test ./api ./grpc ./pubsub ./server ./storage
