# Upon pushing to the main branch it runs all tests.
#
# Copyright (c) 2022 AlertAvert.com.  All rights reserved.
# Author: Marco Massenzio (marco@alertavert.com)
#
name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@v1
      with:
        version: '3.19'

    - name: Install protoc-gen
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

    - name: Build
      run: |
        make build

    - name: Run Containers
      run: |
        mkdir -p ${HOME}/.aws && cp data/credentials ${HOME}/.aws/
        export AWS_REGION=us-west-2
        make services
        sleep 3
        make queues

    - name: Generate Certs
      run: |
        go install github.com/cloudflare/cfssl/cmd/cfssl@v1.6.3
        go install github.com/cloudflare/cfssl/cmd/cfssljson@v1.6.3
        make gencert

    - name: Test
      run: |
        go test ./api ./grpc ./pubsub ./server ./storage
